name: dart_chatgpt
description: chaGPT
version: 1.0.1
repository: https://github.com/paulinofonsecass/chatgpt

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  dio: ^4.0.6
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
