name: dart_chatgpt
description: This plugin enhances the official openAI API including the ChatGPT-3.5-Turbo model 
version: 1.0.2
repository: https://github.com/paulinofonsecass/chatgpt

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  dio: ^4.0.6
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
