name: chatgpt
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/paulinofonsecass/chatgpt

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  dio: ^4.0.6
  hive: ^2.2.3
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
